name: Gsutil
on:
  workflow_dispatch:
jobs:
  copy:
    runs-on: ubuntu-22.04
    steps:
    - name: Copy
      run: |
        pip install gsutil
        gsutil cp gs://kubernetes-release/release/v1.21.1/kubernetes-test-linux-amd64.tar.gz .
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        # TODO: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#configuring-a-custom-artifact-retention-period
        name: kubernetes-test
        path: |
          ./kubernetes-test-linux-amd64.tar.gz
